name: Build web-client
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Clean cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build-web
      - uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./packages/web-clients/dist
